name: packer-base-image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

env:
  VAULT_ADDR: ${{ vars.VAULT_ADDR }}
  VAULT_NAMESPACE: admin # Default namespace on HCP Vault
  VAULT_AUTH_MOUNT: github
  VAULT_HCP_PACKER_PATH: kv/data/shared/hcp-packer
  VAULT_AWS_CREDS_PATH: aws/creds/packer
  PRODUCT_VERSION: latest

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build AMI with Packer
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: "packer init ./ubuntu-base.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate \
            -var vault_addr=${{ env.VAULT_ADDR }} \
            ./ubuntu-base.pkr.hcl

      - name: Install Ansible and CIS Benchmarks role
        id: install-ansible
        if:
          ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy install git+https://github.com/ansible-lockdown/UBUNTU22-CIS.git,tags/1.4.0

      - name: Get HCP credentials
        id: get-hcp-creds
        if:
          ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: hashicorp/hcp-auth-action@v0
        with:
          workload_identity_provider: ${{ env.HCP_WORKLOAD_ID_PROVIDER }}

      - name: Get AWS credentials
        id: get-aws-creds
        if:
          ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ env.VAULT_ADDR }}
          namespace: ${{ env.VAULT_NAMESPACE }}
          path: ${{ env.VAULT_AUTH_MOUNT }}
          method: jwt
          jwtGithubAudience: "${{ github.repository_owner }}-vault"
          secrets: |
            ${{ env.VAULT_AWS_CREDS_PATH }} access_key | AWS_ACCESS_KEY_ID ;
            ${{ env.VAULT_AWS_CREDS_PATH }} secret_key | AWS_SECRET_ACCESS_KEY ;
            ${{ env.VAULT_AWS_CREDS_PATH }} session_token | AWS_SESSION_TOKEN ;

      - name: Run `packer build`
        id: build
        if:
          ${{ github.event_name == 'push' || github.event_name == 'schedule' }}
        run: |
          packer build \
            -var vault_addr=${{ env.VAULT_ADDR }} \
            ./ubuntu-base.pkr.hcl
